"""
Cross-platform network printer discovery.

Windows' spooler reports the *cached* state of a print queue, so a printer that
is switched off, or that moved to a different subnet, still shows up as
``idle``.  The helpers here talk to the device itself instead: a TCP probe of
the usual printing ports plus a real IPP Get-Printer-Attributes request, which
returns the model and live state straight from the hardware.

Pure stdlib, no third-party dependencies, works on Windows/macOS/Linux.

TLS note: every IPPS connection made here uses ``ssl.CERT_NONE`` with hostname
checking disabled, and that is deliberate.  Consumer printers ship a *self-signed*
certificate generated by the device itself, issued to an internal name that never
matches the IP address we dial, and there is no PKI a client could validate it
against.  Verifying would therefore fail on essentially every printer on the
market.  The TLS session here is not an authentication mechanism -- it exists only
because many devices (Epson among them) reset plaintext IPP on 631 -- and nothing
secret is ever sent over it: the request is an unauthenticated
Get-Printer-Attributes, and the reply is the model/state the printer already
announces over mDNS.  Do not copy this ``ssl`` setup into any code path that sends
credentials or fetches data from the internet.
"""

import re
import socket
import ssl
import struct
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Dict, List, Optional, Tuple

from utils.logger import logger

# Ports that indicate "something here speaks a printing protocol"
PRINTER_PORTS: Dict[int, str] = {
    9100: "raw",   # JetDirect / AppSocket
    631: "ipp",    # IPP / IPPS
    515: "lpd",    # LPR
}

# Probed for extra context, but not treated as proof of a printer
EXTRA_PORTS: Dict[int, str] = {80: "http", 443: "https"}

# Best-effort vendor hint from the MAC prefix. Only a fallback for devices that
# refuse IPP -- `printer-make-and-model` from IPP is authoritative when present.
OUI_HINTS: Dict[str, str] = {
    "6855D4": "Seiko Epson",
    "0026AB": "Seiko Epson",
    "A4EE57": "Seiko Epson",
    "008077": "Brother",
    "001B78": "HP",
    "001E8F": "Canon",
}


# ---------------------------------------------------------------- TCP probing


def probe_ports(
    host: str, ports: Optional[List[int]] = None, timeout: float = 0.6
) -> Dict[int, bool]:
    """Check which TCP ports on `host` accept a connection."""
    if ports is None:
        ports = list(PRINTER_PORTS) + list(EXTRA_PORTS)

    def _one(port: int) -> Tuple[int, bool]:
        try:
            with socket.create_connection((host, port), timeout=timeout):
                return port, True
        except OSError:
            return port, False

    with ThreadPoolExecutor(max_workers=len(ports)) as pool:
        return dict(pool.map(_one, ports))


def is_printer_host(open_ports: Dict[int, bool]) -> bool:
    """True if any port specific to printing is open."""
    return any(open_ports.get(p) for p in PRINTER_PORTS)


def open_port_names(open_ports: Dict[int, bool]) -> List[str]:
    """Readable list of the open ports, e.g. ['ipp:631', 'raw:9100']."""
    names = {**PRINTER_PORTS, **EXTRA_PORTS}
    return [f"{names.get(p, 'tcp')}:{p}" for p, is_open in sorted(open_ports.items()) if is_open]


# ----------------------------------------------------------------------- IPP

IPP_STATES = {3: "idle", 4: "processing", 5: "stopped"}

# A Get-Printer-Attributes reply is a few kilobytes. Anything claiming to be
# larger is a broken or hostile device, and we refuse to buffer it: without this
# cap a single host on the scanned subnet could exhaust the client's memory.
MAX_IPP_RESPONSE_BYTES = 1024 * 1024  # 1 MiB

# IPP value tags carrying human-readable text
_TEXT_TAGS = {0x41, 0x42, 0x44, 0x45, 0x47, 0x48, 0x49}
_INT_TAGS = {0x21, 0x23}  # integer, enum
_BOOL_TAG = 0x22

# Vendors disagree on the queue path; these cover the common cases.
DEFAULT_IPP_PATHS = ["/ipp/print", "/ipp/printer", "/printers/ipp", "/"]

_WANTED_ATTRS = [
    b"printer-name",
    b"printer-make-and-model",
    b"printer-state",
    b"printer-state-reasons",
    b"printer-is-accepting-jobs",
    b"printer-location",
    b"printer-info",
    b"printer-uri-supported",
    b"media-default",
    b"media-supported",
    b"sides-supported",
    b"print-color-mode-supported",
    b"printer-resolution-supported",
    b"copies-supported",
    b"media-source-supported",
    b"media-type-supported",
]


def _ipp_attr(tag: int, name: bytes, value: bytes) -> bytes:
    return struct.pack(">BH", tag, len(name)) + name + struct.pack(">H", len(value)) + value


def ipp_printer_uri(host: str, path: str, port: Optional[int] = None, use_tls: bool = False) -> str:
    """The `printer-uri` to advertise for one transport.

    Strict firmware compares this against the URI it is actually serving, so a
    TLS request has to say ``ipps://`` and a non-default port has to be spelled
    out.  Sending ``ipp://host/path`` for an IPPS exchange makes such devices
    reject the request outright, which used to break the 443 fallback.
    """
    scheme = "ipps" if use_tls else "ipp"
    authority = f"{host}:{port}" if port else host
    return f"{scheme}://{authority}{path}"


def _ipp_build_request(
    host: str,
    path: str,
    request_id: int = 1,
    port: Optional[int] = None,
    use_tls: bool = False,
) -> bytes:
    """Encode a minimal IPP/1.1 Get-Printer-Attributes operation."""
    body = struct.pack(">BBHI", 1, 1, 0x000B, request_id)  # version, op-id, request-id
    body += b"\x01"  # operation-attributes-tag
    body += _ipp_attr(0x47, b"attributes-charset", b"utf-8")
    body += _ipp_attr(0x48, b"attributes-natural-language", b"en")
    body += _ipp_attr(0x45, b"printer-uri", ipp_printer_uri(host, path, port, use_tls).encode())
    body += _ipp_attr(0x44, b"requested-attributes", _WANTED_ATTRS[0])
    for attr in _WANTED_ATTRS[1:]:
        # Additional values of one attribute are sent with a zero-length name.
        body += _ipp_attr(0x44, b"", attr)
    body += b"\x03"  # end-of-attributes-tag
    return body


def _ipp_parse_response(data: bytes) -> Dict[str, Any]:
    """Decode the attribute groups of an IPP response into a plain dict."""
    if len(data) < 9:
        return {}
    attrs: Dict[str, Any] = {}
    pos = 8  # skip version(2) + status-code(2) + request-id(4)
    current = None
    while pos < len(data):
        tag = data[pos]
        pos += 1
        if tag == 0x03:  # end-of-attributes
            break
        if tag < 0x10:  # delimiter starting a new attribute group
            current = None
            continue
        if pos + 2 > len(data):
            break
        (name_len,) = struct.unpack(">H", data[pos : pos + 2])
        pos += 2
        name = data[pos : pos + name_len].decode("utf-8", "replace")
        pos += name_len
        if pos + 2 > len(data):
            break
        (val_len,) = struct.unpack(">H", data[pos : pos + 2])
        pos += 2
        raw = data[pos : pos + val_len]
        pos += val_len

        if tag in _TEXT_TAGS:
            value: Any = raw.decode("utf-8", "replace")
        elif tag in _INT_TAGS and val_len == 4:
            value = struct.unpack(">i", raw)[0]
        elif tag == _BOOL_TAG and val_len == 1:
            value = bool(raw[0])
        else:
            continue

        if name:  # a new attribute
            current = name
            attrs[name] = value
        elif current:  # another value belonging to the previous attribute
            existing = attrs[current]
            if isinstance(existing, list):
                existing.append(value)
            else:
                attrs[current] = [existing, value]
    return attrs


def _dechunk(payload: bytes) -> bytes:
    """Reassemble an HTTP chunked body."""
    out, pos = b"", 0
    while pos < len(payload):
        end = payload.find(b"\r\n", pos)
        if end == -1:
            break
        try:
            size = int(payload[pos:end].split(b";")[0], 16)
        except ValueError:
            break
        if size == 0:
            break
        out += payload[end + 2 : end + 2 + size]
        pos = end + 2 + size + 2
    return out


def _as_list(value: Any) -> List[Any]:
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def _ipp_exchange(
    host: str, port: int, path: str, use_tls: bool, timeout: float
) -> Optional[bytes]:
    """POST one IPP request and return the raw HTTP response (capped in size)."""
    body = _ipp_build_request(host, path, port=port, use_tls=use_tls)
    request = (
        f"POST {path} HTTP/1.1\r\n"
        f"Host: {host}:{port}\r\n"
        f"Content-Type: application/ipp\r\n"
        f"Content-Length: {len(body)}\r\n"
        f"Connection: close\r\n\r\n"
    ).encode() + body

    try:
        raw_sock = socket.create_connection((host, port), timeout=timeout)
        if use_tls:
            # Printers ship self-signed certificates; the transport is only
            # used to satisfy the device, we are not authenticating it.
            # See the TLS note in this module's docstring before reusing this.
            ctx = ssl.create_default_context()
            ctx.check_hostname = False
            ctx.verify_mode = ssl.CERT_NONE
            sock = ctx.wrap_socket(raw_sock, server_hostname=host)
        else:
            sock = raw_sock
        with sock:
            sock.settimeout(timeout)
            sock.sendall(request)
            chunks: List[bytes] = []
            received = 0
            while received < MAX_IPP_RESPONSE_BYTES:
                chunk = sock.recv(min(8192, MAX_IPP_RESPONSE_BYTES - received))
                if not chunk:
                    break
                chunks.append(chunk)
                received += len(chunk)
            else:
                # Hostile or broken device streaming without end: take what we
                # have and drop the connection rather than growing forever.
                logger.debug(
                    f"IPP response from {host}:{port}{path} hit the "
                    f"{MAX_IPP_RESPONSE_BYTES} byte cap; truncated"
                )
        return b"".join(chunks)
    except (OSError, ssl.SSLError) as exc:
        logger.debug(f"IPP exchange {host}:{port}{path} (tls={use_tls}) failed: {exc}")
        return None


def ipp_query(
    host: str,
    port: Optional[int] = None,
    timeout: float = 3.0,
    paths: Optional[List[str]] = None,
) -> Optional[Dict[str, Any]]:
    """Ask a device for its own attributes over IPP.

    Tries plain IPP first, then IPPS -- many printers (Epson among them) accept
    connections on 631 but reset anything that is not TLS.  Returns a normalised
    dict, or None if the host answers no variant.
    """
    if port is not None:
        transports = [(port, False), (port, True)]
    else:
        transports = [(631, False), (631, True), (443, True)]

    for use_port, use_tls in transports:
        for path in paths or DEFAULT_IPP_PATHS:
            raw = _ipp_exchange(host, use_port, path, use_tls, timeout)
            if not raw:
                continue

            head, _, payload = raw.partition(b"\r\n\r\n")
            if not head or b" 200 " not in head.split(b"\r\n")[0]:
                continue
            if b"chunked" in head.lower():
                payload = _dechunk(payload)
            attrs = _ipp_parse_response(payload)
            if not attrs:
                continue
            return _normalise_identity(host, use_port, use_tls, path, attrs)
    return None


def _normalise_identity(
    host: str, port: int, use_tls: bool, path: str, attrs: Dict[str, Any]
) -> Dict[str, Any]:
    """Shape raw IPP attributes into the dict the rest of the tool expects."""
    state = attrs.get("printer-state")
    reasons = [r for r in _as_list(attrs.get("printer-state-reasons")) if r != "none"]
    sides = _as_list(attrs.get("sides-supported"))
    scheme = "ipps" if use_tls else "ipp"
    return {
        "host": host,
        "ipp_path": path,
        "ipp_port": port,
        "ipp_tls": use_tls,
        "ipp_uri": f"{scheme}://{host}:{port}{path}",
        "name": attrs.get("printer-name"),
        "make_and_model": attrs.get("printer-make-and-model"),
        "state": IPP_STATES.get(state, "unknown") if isinstance(state, int) else None,
        "state_reasons": reasons,
        "is_accepting_jobs": attrs.get("printer-is-accepting-jobs"),
        "location": attrs.get("printer-location"),
        "info": attrs.get("printer-info"),
        "media_default": attrs.get("media-default"),
        "media_supported": _as_list(attrs.get("media-supported")),
        "media_sources": _as_list(attrs.get("media-source-supported")),
        "media_types": _as_list(attrs.get("media-type-supported")),
        "sides_supported": sides,
        "supports_duplex": any(s.startswith("two-sided") for s in sides),
        "color_modes": _as_list(attrs.get("print-color-mode-supported")),
        "resolutions": _as_list(attrs.get("printer-resolution-supported")),
    }


# ------------------------------------------------------------------- helpers

# Tried in order until one produces addresses; every one of these is stdlib-free
# and present on a default install of its platform.
if sys.platform == "win32":
    _INTERFACE_COMMANDS: List[List[str]] = [["ipconfig"]]
elif sys.platform == "darwin":
    _INTERFACE_COMMANDS = [["ifconfig", "-a"]]
else:
    _INTERFACE_COMMANDS = [["ip", "-4", "addr"], ["ifconfig", "-a"]]


def normalise_mac(mac: str) -> str:
    """'0:1e:8f:a:2:3' or '00-1E-8F-...' -> '00:1E:8F:0A:02:03'."""
    parts = re.split(r"[-:]", mac.strip())
    return ":".join(part.zfill(2).upper() for part in parts)


# macOS' arp prints octets without a leading zero ("0:1e:8f:.."), Windows uses
# dashes and two digits; accept one or two hex digits per octet either way.
_ARP_PATTERN = re.compile(
    r"(\d{1,3}(?:\.\d{1,3}){3}).*?"
    r"\b((?:[0-9a-fA-F]{1,2}[-:]){5}[0-9a-fA-F]{1,2})\b"
)


def arp_table() -> Dict[str, str]:
    """Map IPv4 address -> MAC from the OS neighbour cache."""
    cmd = ["arp", "-a"] if sys.platform == "win32" else ["arp", "-an"]
    try:
        # Not text=True: the ANSI/OEM console codepage on non-English Windows
        # decodes badly under the locale default and used to raise, losing the
        # whole table. Decode as UTF-8 and replace anything unexpected -- the
        # addresses we want are pure ASCII.
        out = subprocess.run(
            cmd,
            capture_output=True,
            encoding="utf-8",
            errors="replace",
            timeout=15,
        ).stdout or ""
    except (OSError, subprocess.SubprocessError) as exc:
        logger.debug(f"arp lookup failed: {exc}")
        return {}

    table: Dict[str, str] = {}
    for line in out.splitlines():
        match = _ARP_PATTERN.search(line)
        if match:
            table[match.group(1)] = normalise_mac(match.group(2))
    return table


def vendor_hint(mac: Optional[str]) -> Optional[str]:
    if not mac:
        return None
    return OUI_HINTS.get(mac.replace(":", "").upper()[:6])


def primary_ipv4() -> Optional[str]:
    """Local address of the interface used for outbound traffic."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.connect(("8.8.8.8", 80))  # no packet is actually sent
            return sock.getsockname()[0]
    except OSError:
        return None


def _interface_ipv4_addresses() -> List[str]:
    """Every IPv4 address this machine has configured, best effort.

    ``primary_ipv4`` only reports the interface holding the default route, which
    on a VPN is the *corporate* interface -- scanning that by default would sweep
    someone else's network.  This enumerates the real interface list instead so
    the caller can tell "my own LAN" from "somewhere else".
    """
    found: List[str] = []

    def _add(candidate: Optional[str]) -> None:
        if candidate and candidate not in found and _is_scannable_address(candidate):
            found.append(candidate)

    _add(primary_ipv4())

    # Hostname resolution: cheap and cross-platform, but often incomplete.
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            _add(info[4][0])
    except (OSError, UnicodeError) as exc:
        logger.debug(f"getaddrinfo for local hostname failed: {exc}")

    for cmd in _INTERFACE_COMMANDS:
        try:
            proc = subprocess.run(
                cmd, capture_output=True, encoding="utf-8", errors="replace", timeout=15
            )
        except (OSError, subprocess.SubprocessError) as exc:
            logger.debug(f"interface lookup {cmd[0]} failed: {exc}")
            continue
        text = proc.stdout or ""
        if not text:
            continue
        for line in text.splitlines():
            if sys.platform == "win32":
                # "IPv4" survives Windows UI localisation; the label around it
                # does not ("IPv4-Adresse", "Adresse IPv4", ...).
                if "IPv4" not in line:
                    continue
                match = re.search(r"(\d{1,3}(?:\.\d{1,3}){3})", line)
                if match:
                    _add(match.group(1))
            else:
                for match in re.finditer(r"\binet\s+(?:addr:)?(\d{1,3}(?:\.\d{1,3}){3})", line):
                    _add(match.group(1))
        if found:
            break  # the first tool that answered told us everything we need

    return found


def _is_scannable_address(ip: str) -> bool:
    """Reject loopback/unspecified/multicast addresses as scan origins."""
    octets = _parse_octets(ip)
    if octets is None:
        return False
    if octets[0] in (0, 127) or octets[0] >= 224:
        return False
    return True


def local_ipv4_networks() -> List[str]:
    """The /24 prefixes this machine itself sits on, e.g. ['192.168.1']."""
    prefixes: List[str] = []
    for ip in _interface_ipv4_addresses():
        prefix = ip.rsplit(".", 1)[0]
        if prefix not in prefixes:
            prefixes.append(prefix)
    return prefixes


def default_subnet() -> Optional[str]:
    """The local /24 as a prefix string, e.g. '192.168.1'."""
    ip = primary_ipv4()
    if ip and _is_scannable_address(ip):
        return ip.rsplit(".", 1)[0]
    networks = local_ipv4_networks()
    return networks[0] if networks else None


# ------------------------------------------------------- subnet validation


def _parse_octets(text: str) -> Optional[List[int]]:
    """Split a dotted string into octets, or None if any part is not 0-255."""
    parts = text.split(".")
    octets: List[int] = []
    for part in parts:
        if not part.isdigit() or (len(part) > 1 and part[0] == "0"):
            return None
        value = int(part)
        if not 0 <= value <= 255:
            return None
        octets.append(value)
    return octets


def normalise_subnet(subnet: str) -> str:
    """Strict /24 prefix: exactly three dotted octets, each 0-255.

    Raises ValueError on anything else -- including a full address, a CIDR
    suffix or a 4th octet -- so a typo can never turn into a sweep of the
    wrong network.
    """
    text = (subnet or "").strip().rstrip(".")
    if text.endswith("/24"):
        text = text[:-3].rstrip(".")
    octets = _parse_octets(text)
    if octets is None or len(octets) != 3:
        raise ValueError(
            f"invalid subnet prefix {subnet!r}: expected exactly three dotted "
            "octets in the range 0-255, e.g. '192.168.1'"
        )
    return ".".join(str(o) for o in octets)


def is_private_prefix(prefix: str) -> bool:
    """True for an RFC1918 or link-local /24 -- i.e. a plausible home LAN."""
    octets = _parse_octets(prefix)
    if octets is None or len(octets) != 3:
        return False
    first, second = octets[0], octets[1]
    if first == 10:
        return True
    if first == 172 and 16 <= second <= 31:
        return True
    if first == 192 and second == 168:
        return True
    if first == 169 and second == 254:  # link-local / APIPA
        return True
    return False


def host_of(text: Optional[str]) -> Optional[str]:
    """Pull an IPv4 address out of a port name, URI or location string."""
    if not text:
        return None
    match = re.search(r"\d{1,3}(?:\.\d{1,3}){3}", text)
    return match.group(0) if match else None


# --------------------------------------------------------------- the scan

# Each worker probes 5 ports concurrently, so the real socket count is roughly
# 5x this. 64 workers meant ~320 simultaneous connects, which trips consumer
# router connection limits and reads as a SYN flood to network monitoring.
DEFAULT_SCAN_WORKERS = 32
MAX_SCAN_WORKERS = 64


def inspect_host(host: str, timeout: float = 0.6, deep: bool = True) -> Optional[Dict[str, Any]]:
    """Probe one host and, if it looks like a printer, identify it via IPP."""
    open_ports = probe_ports(host, timeout=timeout)
    if not is_printer_host(open_ports):
        return None

    entry: Dict[str, Any] = {
        "host": host,
        "open_ports": open_port_names(open_ports),
        "protocols": [name for port, name in PRINTER_PORTS.items() if open_ports.get(port)],
        "reachable": True,
    }
    if deep and open_ports.get(631):
        identity = ipp_query(host, timeout=max(timeout * 4, 3.0))
        if identity:
            entry["ipp"] = identity
            entry["model"] = identity.get("make_and_model")
            entry["state"] = identity.get("state")
    return entry


def _refusal(message: str, subnet: Optional[str]) -> Dict[str, Any]:
    """The shape the CLI layer turns into a 400, not a crash or a 500."""
    return {
        "code": 400,
        "msg": message,
        "error": message,  # older callers look for `error`
        "subnet": subnet,
        "printers": [],
        "count": 0,
    }


def scan_subnet(
    subnet: Optional[str] = None,
    timeout: float = 0.6,
    workers: int = DEFAULT_SCAN_WORKERS,
    deep: bool = True,
    force: bool = False,
) -> Dict[str, Any]:
    """Sweep a /24 for hosts speaking a printing protocol.

    A scan opens hundreds of TCP connections to every address in the range, which
    on somebody else's network is indistinguishable from a port sweep.  So unless
    `force` is set, the prefix has to be either one this machine is actually
    attached to, or a private (RFC1918/link-local) range -- a typo like
    `--subnet 8.8.8`, or a corporate range reachable only because a VPN owns the
    default route, is refused instead of scanned.
    """
    requested = subnet
    if subnet:
        try:
            subnet = normalise_subnet(subnet)
        except ValueError as exc:
            return _refusal(str(exc), requested)
    else:
        subnet = default_subnet()

    if not subnet:
        return {"subnet": None, "printers": [], "count": 0, "error": "no local IPv4 network found"}

    if not force:
        local = local_ipv4_networks()
        if subnet not in local and not is_private_prefix(subnet):
            return _refusal(
                f"refusing to scan {subnet}.0/24: it is not one of this machine's "
                f"own networks ({', '.join(f'{p}.0/24' for p in local) or 'none found'}) "
                "and it is not a private range. Scanning it would port-sweep a "
                "network you may not own. Pass --force if you are certain.",
                subnet,
            )

    workers = max(1, min(int(workers), MAX_SCAN_WORKERS))
    hosts = [f"{subnet}.{n}" for n in range(1, 255)]
    macs = arp_table()

    found: List[Dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=workers) as pool:
        for entry in pool.map(lambda h: inspect_host(h, timeout, deep), hosts):
            if entry:
                mac = macs.get(entry["host"])
                entry["mac"] = mac
                entry["vendor_hint"] = vendor_hint(mac)
                found.append(entry)

    found.sort(key=lambda e: tuple(int(p) for p in e["host"].split(".")))
    return {"subnet": f"{subnet}.0/24", "printers": found, "count": len(found)}
